BTDT/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#home', as: 'home' #WORKING
  get '/login', to: 'users#login', as: 'login' #WORKING
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  resources :posts#WORKING
  resources :comments, only: [:new, :create, :show, :edit, :update, :destroy]#WORKING
  resources :users#WORKING
  resources :countries, only: [:index, :show]#WORKING
  resources :visits, only: [:new, :create, :show]#WORKING
  resources :sessions, only: [:create, :new, :destroy]
end

BTDT/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BTDT</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">Been There Done That!</a>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Home', home_path, class: "nav-item nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Users', users_path, class: "nav-item nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Posts', posts_path, class: "nav-item nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'All Countries', countries_path, class: "nav-item nav-link" %>
      </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">

      <li class="nav-item">
        <% if session[:user_id] %>
        <% current_user = User.all.find(session[:user_id])%>
          <%= link_to ("Welcome " + current_user.name + "!!"), user_path(current_user), class: "nav-item nav-link" %>
        <% else %>
          <%= link_to 'Sign Up', new_user_path, class: "nav-item nav-link" %>
        <% end %>
      </li>
      <li class="nav-item">
        <% if session[:user_id] %>
          <%= link_to 'Log Out', logout_path, class: "nav-item nav-link" %>
        <% else %>
          <%= link_to 'Log In', login_path, class: "nav-item nav-link" %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

<div class="container">
<br>
<br>
<br>
    <%= yield %>
</div>
  </body>
</html>