BTDT/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#home', as: 'home' #WORKING
  get '/login', to: 'users#login', as: 'login' #WORKING
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  resources :posts#WORKING
  resources :comments, only: [:new, :create, :show, :edit, :update, :destroy]#WORKING
  resources :users#WORKING
  resources :countries, only: [:index, :show]#WORKING
  resources :visits, only: [:new, :create, :show]#WORKING
  resources :sessions, only: [:create, :new, :destroy]
end

BTDT/app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    # accepts_nested_attributes_for :comments
end

BTDT/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index#WORKING
    @posts = Post.all
  end

  def new#WORKING
    @user = User.find_by(id: session[:user_id])
    @post = Post.new
  end

  def create#WORKING
    @user = User.find_by(id: session[:user_id])
    @post = Post.new(post_params)
    @post.user_id = session[:user_id]
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show#WORKING
    @comment = Comment.new
    this_post
  end

  def edit#WORKING
    this_post
  end

  def update#WORKING
    this_post
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  # def new_comment
  #   @post = Post.find(params[:id])
  #   #render new view page
  # end
  #
  # def new_comment_create
  #   @post.comments.build(comment_params)
  # end

  def destroy#WORKING
    this_post.destroy
    redirect_to posts_path
  end
################################################################
private

  def post_params
    params.require(:post).permit(:title, :content, :attributes, comments_attributes: [:text, :attributes])
  end

  def this_post
    @post = Post.find(params[:id])
  end
end

BTDT/app/helpers/posts_helper.rb
module PostsHelper
end

BTDT/app/views/posts/edit.html.erb
<div class="card">
    <div class="card-body">
    <h1 class="card-title">Edit Post</h1>

<%= form_for @post do |f| %>
  Title : <%= f.text_field :title %><br>
  Content : <%= f.text_field :content %><br>
  <%= f.submit "Edit Post", :class => 'btn btn-primary' %>
<% end %>
</div>
</div>

BTDT/app/views/posts/index.html.erb
<div class="card">
    <div class="card-body">
    <h1 class="card-title">All Posts</h1>

 <ul>
   <% @posts.each do |p| %>
   <li><%= link_to p.title, post_path(p) %> by <%= p.user.name %></li>
        <%= p.content %><br><br>
   <% end %>
 </ul>
 
 </div>
 </div>

BTDT/app/views/posts/new.html.erb
<div class="card">
    <div class="card-body">
    <h1 class="card-title">New Post</h1>

<%= form_for @post do |f| %>
  Post Title: <%= f.text_field :title %><br>
  Content: <%= f.text_field :content %><br>
  
  <%= f.submit "Make Post", :class => 'btn btn-primary' %>
<% end %>

</div>
</div>

BTDT/app/views/posts/show.html.erb
<div class="card">
    <div class="card-body">
    <h1 class="card-title"><%= @post.title %></h1>

<h2>By <%= link_to @post.user.name, user_path(@post.user) %></h2>

<p><%= @post.content %></p>
</div>
</div>

<br>
<br>

<div class="card">
    <div class="card-body">
    <h3 class="card-title">Comments</h3>
<ul>
  <% @post.comments.each do |c|%>
    <%= c.text %><br>
    <%= link_to "Edit", edit_comment_path(c)%>  |
    <%= link_to('Delete', comment_path(c), method: :delete, data: {confirm: 'Are you sure?'}) %><br>
  <% end %>
</ul>

<%= form_for @comment do |f| %>
  Comment : <%= f.text_area :text %><br />
  <%= f.hidden_field :post_id, :value => @post.id %>
  <%= f.submit :post, :value => "Submit Comment", :class => 'btn btn-primary' %>
<% end %>

<% if session[:user_id] == @post.user.id %>
  <%= link_to "Edit Post", edit_post_path(@post) %><br>
  <%= link_to('Delete Post', post_path(@post), method: :delete, data: {confirm: "Are you sure?"}) %><br>
  <%= link_to('Profile Page', user_path(@post.user.id)) %><br>
<% end %>
</div>
</div>