BTDT/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#home', as: 'home' #WORKING
  get '/login', to: 'users#login', as: 'login' #WORKING
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  resources :posts#WORKING
  resources :comments, only: [:new, :create, :show, :edit, :update, :destroy]#WORKING
  resources :users#WORKING
  resources :countries, only: [:index, :show]#WORKING
  resources :visits, only: [:new, :create, :show]#WORKING
  resources :sessions, only: [:create, :new, :destroy]
end

BTDT/app/models/user.rb
class User < ApplicationRecord
    has_secure_password 
    has_many :visits, dependent: :destroy
    has_many :countries, through: :visits
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy

    validates :name, presence: true 
    validates :password, presence: true


    def most_points
        User.all.max_by { |user| user.points }
    end

    def avg_visits_per_user
        User.all.average(:visits)
    end


    def bonus_points
      @num_of_visits = self.visits.length
      if @num_of_visits > 15
        self.points += 100
      elsif @num_of_visits > 10
        self.points += 50
      elsif @num_of_visits > 5
        self.points +=  10
      end
    end

    def num_of_countries
      self.countries.uniq.length
    end

####################LEADER BOARD METHODS###########################
    def self.sort_by_points#WORKING
      all.sort_by {|u| u.points}.reverse
    end

    def self.sort_by_countries#WORKING
      User.all.sort_by{|u| u.countries.uniq.length}.reverse
    end

    def self.sort_by_visits#WORKING
      User.all.sort_by{|u| u.visits.length}.reverse
    end

    def my_rank_by_countries#WORKING
      rank = User.sort_by_countries.index {|u| u.name == self.name} + 1
      rank
    end

    def my_rank_by_points#WORKING
      rank = User.sort_by_points.index {|u| u.name == self.name} + 1
      rank
    end

    def my_rank_by_visits#WORKING
      rank = User.sort_by_visits.index {|u| u.name == self.name} + 1
      rank
    end

    def title#WORKING
      #based on num of countries visited
      num = self.num_of_countries
      if num > 50
        "World Traveler"
      elsif num > 21
        "Professional Tourist. 'I Live Abroad'"
      elsif num > 11
        "Frequent Flyer. 'Look at You'"
      elsif num > 5
        "Above Average. 'Out and About!''"
      elsif num > 3
        "Average 'Eh. Nothing Special'"
      else
        "Couch Potato 'You need to get out more'"
      end
    end
end

BTDT/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def home
      @users = User.all
      @rank_by_points = User.sort_by_points[0..4]
      @rank_by_countries = User.sort_by_countries[0..4]
      @most_visited_countries = Country.sort_by_visits[0..9]
    end
    #   redirect_to login_path

    def index
      @users = User.all
    end

    def new
        @user = User.new
    end

    def login
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        @user.points = 0
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
      @user = User.find(params[:id])
      @posts = @user.posts[0..4]
    end

    def edit
      @user = User.find(params[:id])
    end

    def update###WORKING###
        @user = User.find(params[:id])  
        @user.profile_pic = params["user"][:profile_pic]
        @user.age = params["user"][:age]
        @user.country_of_origin = params["user"][:country_of_origin]
        if @user.save!(validate: false)
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :edit
        end
    end

    def destroy #WORKING
      @user = User.find(params[:id])
        @user.destroy
        session[:user_id] = nil
      redirect_to home_path
    end

    private
    def user_params
        params.require(:user).permit(:name, :age, :country_of_origin, :profile_pic, :password, :password_confirmation)
    end
end

BTDT/app/views/users/edit.html.erb
<div class="card">
    <div class="card-body">
    <h1 class="card-title">Edit Your Profile</h1>

<%= form_for @user do |f| %>
  New Profile Picture: <%= f.text_field :profile_pic %><br>
  Age: <%= f.text_field :age %><br>
  Country of Origin: <%= f.text_field :country_of_origin %><br>
  <%= f.submit "Edit User", :class => 'btn btn-primary' %>
<% end %>

  </div>
</div>

BTDT/app/views/users/home.html.erb
<div class="jumbotron">
  <h1 class="display-3">Been There Done That!</h1>
  <p class="lead">The place for world travelers to see and be seen</p>
  <hr class="my-4">
  <p>Rank yourself, see where others stand and be inspired to travel more.</p>
  <p class="lead">
    <%= link_to "Get Started", new_user_path, :class => 'btn btn-primary btn-lg' %>
  </p>
</div>


<div class="container-center">
  <div class="row">
    <div class="col-sm-5">

  <div class="card">
  <div class="card-body">
    <h2 class="card-title">MOST POINTS</h2>
    <table class="table table-hover">
        <thead>
          <tr>
          </tr>
        </thead>
        <tbody>
          <% @rank_by_points.each do |u| %>
          <tr class="table-active">
            <th scope="row"><%= link_to u.name, user_path(u) %></th>
            <td><%= u.points %></td>
            </tr>
            <% end %>
        </tbody>
      </table>
  </div>
</div>
</div>

    <div class="col-sm-5">
      <div class="card">
    <div class="card-body">
    <h2 class="card-title">MOST COUNTRIES</h2>
        <table class="table table-hover">
        <thead>
          <tr>
          </tr>
        </thead>
        <tbody>
          <% @rank_by_countries.each do |u| %>
          <tr class="table-active">
            <th scope="row"><%= link_to u.name, user_path(u) %></th>
            <td><%= u.num_of_countries %></td>
            </tr>
            <% end %>
        </tbody>
      </table>
     </div>
</div>
</div>
</div>
<br>
<br>
<div class="container-center">
  <div class="col-sm-10">
<div class="card">
    <div class="card-body">
    <h2 class="card-title">MOST POPULAR COUNTRIES</h2>
<table class="table table-hover">
        <thead>
          <tr>
          </tr>
        </thead>
        <tbody>
          <% @most_visited_countries.each do |c| %>
          <tr class="table-active">
            <th scope="row"><%= c.flag_emoji %> <%= link_to c.name, country_path(c) %></th>
            <td><%= c.visits.length %></td>
            </tr>
            <% end %>
        </tbody>
      </table>
      </div>
      </div>
  </div>
</div>

<br/>
<br/>
<nav class="navbar bottom navbar-light bg-light">
<p>Made with ♡ by <a href="https://github.com/dekadekadeka">Deka Ambia</a>, <a href="https://github.com/PrestonElliott">Preston Elliott</a>, and <a href="https://github.com/seeRoseCode">Kesha Rose Lake</a></p>
<p><a href="https://www.youtube.com/watch?v=piGMwFb833U">Video Demo</a></p>
</nav>

BTDT/app/views/users/index.html.erb
<div class="card">
    <div class="card-body">
    <h1 class="card-title">USERS</h1>
<ul style="list-style: none;">
  <% @users.each do |u| %>
  <li><%= link_to u.name, user_path(u) %></li> <br>

  <% end %>
</ul>
</div>
</div>

BTDT/app/views/users/login.html.erb
<div class="card">
    <div class="card-body">
    <h1 class="card-title">Log In</h1>

<p><%= alert %></p>
<%= form_for @user, url: login_path, method: 'POST' do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit "Login", :class => 'btn btn-primary' %>
<% end %>
</div>
</div>

BTDT/app/views/users/new.html.erb
<div class="card">
    <div class="card-body">
    <h1 class="card-title">Create An Account</h1>
<%= form_for @user, controller: 'users', action: 'create' do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Create Account", :class => 'btn btn-primary' %>
<% end %>
</div>
</div>

BTDT/app/views/users/show.html.erb
<div class="card">
    <div class="card-body">
    <h1 class="card-title"><%= @user.name %></h1>
<img src="<%= @user.profile_pic %>" alt="My Profile Pic" style=" display: block; margin-left: auto; margin-right: auto; width: 40%;"><br>
<h2 style="text-align:center;">Level: <%= @user.title %></h2>
<h3> Ranking </h3>
<ul>
<li># <%= @user.my_rank_by_countries %> in Countries visited!</li>
<li># <%= @user.my_rank_by_points %> in Points Accumulated!</li>
<li># <%= @user.my_rank_by_visits %> in Trips Taken!</li>
</ul>




<h3>Points: <%= @user.points %></h3>
<ul>
  <li>Age: <%= @user.age %></li>
  <li>Country of Origin: <%= @user.country_of_origin %></li>
</ul>

<br><hr><br>

<h3>VISITS</h3>
<h4>Total Visits: <%= @user.visits.length %></h4><br><br>
<h4>Countries Visited</h4>
<ul>
  <% @user.countries.uniq.each do |c| %>
    <li><%= link_to c.name, country_path(c) %> <%= c.flag_emoji %></li>
  <% end %>
</ul>

<br><hr><br>
<h3>POSTS</h3>
<% if @posts.length > 0 %>
  <% @posts.each do |p|%>
    <li><%= link_to p.title, post_path(p) %></li>
    <p><%=p.content %></p>
  <% end %>
<% else %>
  You don't have any posts <br><br>
<% end %>


<% if session[:user_id] == @user.id %>
    <br><hr><br>
  <%= link_to "Create New Trip", new_visit_path %><br>
  <%= link_to "Create New Post", new_post_path(@user) %><br>
  <%= link_to "Edit Profile", edit_user_path(@user) %><br>
  <%= link_to('Delete Profile', user_path(@user), method: :delete, data: {confirm: "Are you sure?"}) %><br>
<% end %>
</div>
</div>